name: DevSecOps Pipeline
on:
  push:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # resolve o aviso de Node.js

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    # 🔍 SAST
    - name: Run Semgrep
      run: |
        pip install semgrep
        semgrep --config=auto . --json > semgrep.json

    # 📦 SCA - Cache do banco de dados entre runs
    - name: Cache Dependency Check DB
      uses: actions/cache@v4
      with:
        path: ~/.dependency-check/data
        key: dependency-check-db-${{ runner.os }}

    - name: Dependency Check
      run: |
        wget -q https://github.com/jeremylong/DependencyCheck/releases/download/v12.1.0/dependency-check-12.1.0-release.zip
        unzip -q dependency-check-12.1.0-release.zip
        ./dependency-check/bin/dependency-check.sh \
          --scan . \
          --format JSON \
          --out reports \
          --nvdApiKey ${{ secrets.NVD_API_KEY }} \
          --data ~/.dependency-check/data \
          --failOnCVSS 7
      continue-on-error: true

# 🐳 Subir app
    - name: Run app
      run: docker compose -f docker/docker-compose.yml up -d

    - name: Wait for app to be ready
      run: |
        echo "Aguardando app subir..."
        for i in {1..15}; do
          curl -s http://localhost:5000 && echo "App pronta!" && break
          echo "Tentativa $i..."
          sleep 3
        done

    # 🌐 DAST
    - name: Run ZAP
      run: |
        docker run -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
          -t http://localhost:5000 \
          -r zap_report.html
      continue-on-error: true  # ← precisa estar aqui

    # 📁 Salvar relatórios
    - name: Upload reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          semgrep.json
          reports/
          zap_report.html
